// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Revisao.CoreData.Context;

namespace Revisao.CoreData.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20191217010521_CreateTableProduto")]
    partial class CreateTableProduto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Revisao.CoreDomain.Entities.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<int?>("TipoProdutoid");

                    b.Property<decimal>("Valor");

                    b.HasKey("id");

                    b.HasIndex("TipoProdutoid");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Revisao.CoreDomain.Entities.TipoProduto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("id");

                    b.ToTable("TipoProduto");
                });

            modelBuilder.Entity("Revisao.CoreDomain.Entities.Produto", b =>
                {
                    b.HasOne("Revisao.CoreDomain.Entities.TipoProduto", "TipoProduto")
                        .WithMany()
                        .HasForeignKey("TipoProdutoid");
                });
#pragma warning restore 612, 618
        }
    }
}
