// <auto-generated />
namespace Cs483.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class CreatetableProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatetableProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201912022346037_CreatetableProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
